### ISSUE TITLE
[Feature Request] uuid snippet

### ISSUE THREAD

**Issue by GR3YH4TT3R93** [rafamadriz/friendly-snippets#395] opened 2024-01-12 20:03 UTC
I just converted from CoC and honza/snippets but one little feature I really miss is the ability to have a random uuid generator snippet like honza's UltiSnips uuid snippet.

Is it possible to add to LuaSnip rather than UltiSnip? 

For reference, I checked out TrevorS/uuid-nvim but I'd like to have it as a snippet available for cmp rather than a keybind for dx consistency if at all possible.

Ps, thanks to all the contributors for the amazing work that has been put into this project!

**Comment by ybc37** [comment] 2024-01-14 22:28
Have a look at this PR I opened recently: https://github.com/rafamadriz/friendly-snippets/pull/386. It just adds an UUIDv4 snippet in the global scope. Is this what you're looking for?

**Comment by GR3YH4TT3R93** [comment] 2024-01-15 05:48
Yes! This is exactly what I was looking for!

**Comment by GR3YH4TT3R93** [comment] 2024-01-24 14:16
After testing, it doesn't seem to work

**Comment by ybc37** [comment] 2024-01-24 17:59
That's strange, I use it like that with Neovim + nvim-cmp + LuaSnip without issues. Do other LSP builtin variables ([1], [2]) work for you (e.g. [date](https://github.com/rafamadriz/friendly-snippets/blob/main/snippets/global.json#L16) snippet)? I'm not an expert, so there could be something wrong with the snippet, too :smile: 

[1] https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables
[2] https://github.com/L3MON4D3/LuaSnip/blob/2dbef19461198630b3d7c39f414d09fb07d1fdd2/lua/luasnip/util/_builtin_vars.lua

**Comment by GR3YH4TT3R93** [comment] 2024-01-24 18:31
It's not even showing up for me as a snippet tbh. As for other variable snippets like date, they work as expected. I would assume it would work if it were available but for some reason it's not even showing up
![lorem](https://github.com/rafamadriz/friendly-snippets/assets/76727386/395c6182-5dca-4548-80ea-3ff21201ecd5)
![uuid](https://github.com/rafamadriz/friendly-snippets/assets/76727386/a79e3b73-78f2-426c-9c2d-ffc21506e6f4)
![date](https://github.com/rafamadriz/friendly-snippets/assets/76727386/6c4dbee8-d966-4c1a-aa08-4daa0c2da9c9)
![date](https://github.com/rafamadriz/friendly-snippets/assets/76727386/852fc9d8-5172-46ba-8cb9-376ead422213)

**Comment by ybc37** [comment] 2024-01-24 21:23
I think the problem is that you use the `main` branch of my fork. But the uuid snippet is in the branch `feature/global-uuid`: https://github.com/ybc37/friendly-snippets/tree/feature/global-uuid

I guess something like that should work (can't test it right now):

```lua
dependencies {
  -- [...]
  { 
    "ybc37/friendly-snippets",
    branch = "feature/global-uuid"
  },
  -- [...]
},
```

I hope the PR gets merged soon :)

**Comment by GR3YH4TT3R93** [comment] 2024-01-24 23:18
Wow I'm dumb... lol sorry about that

It works perfectly now!

**Comment by OkelleyDevelopment** [comment] 2024-02-12 05:16
Closing this issue as [386](https://github.com/rafamadriz/friendly-snippets/pull/386) is merged!

@GR3YH4TT3R93 @ybc37

**Closed by OkelleyDevelopment** 2024-02-12 05:16 UTC
