### ISSUE TITLE
Cannot trigger any rails snippet on a ruby file

### ISSUE THREAD

**Issue by JuanVqz** [rafamadriz/friendly-snippets#262] opened 2023-03-03 05:02 UTC
According to the README, we should be able to add frameworks snippets with the following line but didn't work

https://github.com/JuanVqz/dotfiles/blob/6d2d68402e9cbe363f74a5db058677dabdda14b5/config/nvim/lua/user/plugins/luasnip.lua#L4

[Here ](https://github.com/JuanVqz/dotfiles/blob/6d2d68402e9cbe363f74a5db058677dabdda14b5/config/nvim/lua/user/plugins.lua#L137)is how I'm calling this plugin in my config file, is it right?

Thank you for your help! :+1:

**Comment by OkelleyDevelopment** [comment] 2023-03-04 05:47
Hi @JuanVqz, I'll take a look and see where the issue is arising from. Will keep you updated on what I find

**Comment by OkelleyDevelopment** [comment] 2023-03-12 19:24
Hi again @JuanVqz, 

I haven't forgotten about this issue, just had a lot of stuff to handle last week that I didn't foresee. Nonetheless, I might have *part* of the issue figured out. 

- You may need to insert this line `require("luasnip/loaders/from_vscode").lazy_load()` just before you extend the filetype snippets. 
- If that doesn't fix the issue, then I would be interested to know if you can see the regular ruby snippets (just checking that the issue isn't elsewhere in the config setup).

Let me know and I'll do my best to help close this issue out :sunglasses:

**Comment by JuanVqz** [comment] 2023-03-13 15:09
> * require("luasnip/loaders/from_vscode").lazy_load()

Thank you for taking the time, no rush

adding the line didn't work, and yes the regular ruby snippets work pretty fine.

![image](https://user-images.githubusercontent.com/7331511/224743536-fed4e919-b0c9-4337-9d9a-f3e6fcb4f544.png)

**Comment by OkelleyDevelopment** [comment] 2023-03-29 06:47
Hey @JuanVqz, after some more thinking: I'm not sure of the problem :sweat: 

My next idea: try extending snippets like this (after your initial `pcall()` check that way it doesn't crash)
```lua
require("luasnip").filetype_extend("ruby", { "rails" })
```

Hopefully this helps us get some progress

**Comment by JuanVqz** [comment] 2023-04-17 17:43
> 

Hi! @OkelleyDevelopment sadly, it doesn't work as well :(

**Comment by rafamadriz** [comment] 2023-04-30 22:40
Hello @JuanVqz sorry for the late response, it seems like the problem is lazy loading the snippets with `require("luasnip.loaders.from_vscode").lazy_load()`. So whatever is the place in your config where you're loading vscode snippets, make sure to use `require("luasnip.loaders.from_vscode").load()`. Then calling `require("luasnip").filetype_extend("ruby", { "rails" })` should work just fine.

Here's a minimal config where	 I got it working:

```lua
local on_windows = vim.loop.os_uname().version:match "Windows"

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv "TEMP" or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local function load_plugins()
    require("packer").startup {
        {
            "wbthomason/packer.nvim",
            "L3MON4D3/LuaSnip",
            "hrsh7th/nvim-cmp",
            "saadparwaiz1/cmp_luasnip",
            "rafamadriz/friendly-snippets",
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    }
end

_G.load_config = function()
    local cmp = require "cmp"

    cmp.setup {
        snippet = {
            expand = function(args) require("luasnip").lsp_expand(args.body) end,
        },
        mapping = cmp.mapping.preset.insert {
            ["<C-b>"] = cmp.mapping.scroll_docs(-4),
            ["<C-f>"] = cmp.mapping.scroll_docs(4),
            ["<C-Space>"] = cmp.mapping.complete(),
            ["<C-e>"] = cmp.mapping.abort(),
            ["<CR>"] = cmp.mapping.confirm { select = true },
        },
        sources = cmp.config.sources {
            { name = "luasnip" },
        },
    }

    require("luasnip.loaders.from_vscode").load()
    require("luasnip").filetype_extend("ruby", { "rails" })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path }
    load_plugins()
    require("packer").sync()
    vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
    load_plugins()
    require("packer").sync()
    _G.load_config()
end
```

Here you can see I'm getting rails snippets in a ruby file:

[Screencast from 2023-04-30 19-37-10.webm](https://user-images.githubusercontent.com/67771985/235379152-f914e21d-d102-4ae3-a8cd-0dfb6cacd901.webm)

I'm gonna add that to the README so people know they have to use `require("luasnip.loaders.from_vscode").load()` to load frameworks snippets

**Comment by rafamadriz** [comment] 2023-05-01 00:35
Found an issue in folke/lazy.nvim#266 that seems to be the same problem as this one (I think?). Folke mentions it [here](https://github.com/folke/lazy.nvim/issues/266#issuecomment-1368271202) and [here](https://github.com/folke/lazy.nvim/issues/266#issuecomment-1368274567). So yeah definitely don't use `lazy_load()`. Closing for now as this seems resolved, open if needed.

**Closed by rafamadriz** 2023-05-01 00:35 UTC
Labels: information and testing

**Comment by JuanVqz** [comment] 2023-05-01 21:29
Thank you for your help!

yes, it is working now :partying_face: 

https://github.com/JuanVqz/dotfiles/commit/b1693195b2949a3d13c2e31d2d0c6ccd74b6d9aa#diff-6cdf21ad847df0edeedef23ffb4f33b6d5d08624759306dca1b3be36b2156616

**Comment by rafamadriz** [comment] 2023-05-04 00:17
@JuanVqz I'm glad it works now, however I did some more testing and you can make it work using `lazy_load()`, but you need to make sure to add `friendly-snippets` as a dependencie for `LuaSnip`. And actually I now recommend this way because not lazy-loading has a very noticeable impact in performance, at least it did in my machine and I'm not the only one (#276). So if you notice a slower startuptime, use `lazy_load()` and add the snippets as a dependencie

**Comment by zach-is-my-name** [comment] 2023-09-02 23:38
Hi!
Can you clear something up? I have a hunch that the above scenario of using framework extensions are different than try to extend your javascript snippets into my typescript-react filetypes. 

I solved this by modifying the package.json file as such:
            {
                "language": ["typescript", "typescriptreact"],
                "path": "./snippets/javascript/typescript.json"
            },
++++++++++  {
++++++++++      "language": ["typescript", "typescriptreact"],
++++++++++      "path": "./snippets/javascript/javascript.json"
++++++++++  },

But I originally thought I could handle it the way it's being done above, but gave up.  
 ```
 {
    'L3MON4D3/LuaSnip',
    enabled = true,
    after = 'hrsh7th/nvim-cmp',
    dependencies = { "rafamadriz/friendly-snippets" },

    config = function()
			require("luasnip.loaders.from_vscode").lazy_load({})
      require("luasnip").filetype_extend("typescriptreact", { "javascript" })
    end,
  }
```
Can you confirm one approach over another, if not for me, but the next person who tries to solve this?
