### ISSUE TITLE
Can't use `django-rest` snippets

### ISSUE THREAD

**Issue by aleprovencio** [rafamadriz/friendly-snippets#210] opened 2022-11-28 20:32 UTC
I'm able to load `django` snippets just fine with this:
```
luasnip.filetype_extend('python', { 'django' })
```

However, I can't make `django-rest` work likewise:
```
luasnip.filetype_extend('python', { 'django-rest' })
```

This also loads `django` snippets but not `django-rest`'s:
```
luasnip.filetype_extend('python', { 'django', 'django-rest' })
```

Is there something wrong?

**Comment by OkelleyDevelopment** [comment] 2022-11-29 02:42
Hey @aleprovencio :wave:

In my configuration I have: 

```lua
require("luasnip/loaders/from_vscode").lazy_load()
require("luasnip").filetype_extend("python", { "django-rest" })
```
and it seems to be working (even when I modify it like in your third example above). 

Some ideas: 

- If you try to access the snippet `sdate`, does anything load? 
- Have you run `:PackerCompile` ? (I doubt this would be the issue, but worth a try)
- Could you link your config by chance?

Let me know what you find and we can continue solving this mystery :sunglasses:

**Comment by aleprovencio** [comment] 2022-11-29 10:56
Thanks for your help @OkelleyDevelopment !

> ```lua
> require("luasnip/loaders/from_vscode").lazy_load()
> require("luasnip").filetype_extend("python", { "django-rest" })
> ```

This is what I use too.

> - If you try to access the snippet `sdate`, does anything load?

I've had not tested snippets from the `django_rest/serialiazers.json` until you mentioned it, and they are indeed working 😄
I just have to find out why snippets from the `django_rest/views.json` are still not working, like `createapiview`

> - Have you run `:PackerCompile` ? (I doubt this would be the issue, but worth a try)

Yeap

> - Could you link your config by chance?

Sure,

```lua
-- protected call
local cmp_ok, cmp = pcall(require, 'cmp')
if not cmp_ok then
  return
end
local snip_ok, luasnip = pcall(require, 'luasnip')
if not snip_ok then
  return
end

-- Load snippets
---- all but frameworks
require('luasnip.loaders.from_vscode').lazy_load()
---- from frameworks
luasnip.filetype_extend('python', { 'django-rest' })

-- Load icons
local icons = require 'aleprovencio.utils.icons'
local kind_icons = icons.kind

-- Setup nvim-cmp
cmp.setup {
  snippet = {
    expand = function(args)
      luasnip.lsp_expand(args.body)
    end,
  },
  mapping = cmp.mapping.preset.insert {
    ['<C-u>'] = cmp.mapping.scroll_docs(-4),
    ['<C-d>'] = cmp.mapping.scroll_docs(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-y>'] = cmp.config.disable,
    ['<C-e>'] = cmp.mapping { i = cmp.mapping.abort(), c = cmp.mapping.close() },
    ['<CR>'] = cmp.mapping.confirm { select = false },
    ['<Tab>'] = cmp.mapping(function(fallback)
      if luasnip.expand_or_locally_jumpable() then
        luasnip.expand_or_jump()
      else
        fallback()
      end
    end, { 'i', 's' }),
    ['<S-Tab>'] = cmp.mapping(function(fallback)
      if luasnip.jumpable(-1) then
        luasnip.jump(-1)
      else
        fallback()
      end
    end, { 'i', 's' }),
  },
  sources = cmp.config.sources({
    { name = 'nvim_lsp' },
    { name = 'luasnip' },
    { name = 'path' },
    { name = 'emoji' },
  }, {
    { name = 'buffer' },
  }),
  confirm_opts = { behavior = cmp.ConfirmBehavior.Replace, select = false },
  window = {
    documentation = {
      border = icons.ui.Borders,
    },
  },
  experimental = { ghost_text = false },
  formatting = {
    fields = { 'kind', 'abbr', 'menu' },
    format = function(entry, vim_item)
      -- Kind icons
      vim_item.kind = string.format('%s', kind_icons[vim_item.kind])
      vim_item.menu = ({
        nvim_lsp = '[LSP]',
        luasnip = '[Snippet]',
        buffer = '[Buffer]',
        path = '[Path]',
      })[entry.source.name]
      return vim_item
    end,
  },
}
```

**Comment by OkelleyDevelopment** [comment] 2022-11-29 18:42
Thanks for getting back on this @aleprovencio :raised_hands: 

I'll take a look at those snippets shortly and get back with any potential fix(es)!

**Comment by OkelleyDevelopment** [comment] 2022-11-30 22:24
Good news @aleprovencio, I believe the snippets are fixed now!

It seemed that there were some missing commas on the "body" portion of the `ViewSet` snippet at the end of the file. With those now added in (and the branch merged upstream to here), the snippets should be working as expected. 

Now all you have to do is:
- `:PackerSync friendly-snippets`
- Open your django project and resume working :mechanical_arm:  

As always, I'll leave this issue open until you have confirmed things are working on your end :sunglasses:

**Closed** 2022-12-01 13:51 UTC
Labels: bug, In progress
